import io from 'socket.io-client';

let base = "http://localhost:57446/api";

//Map
let map = base+"/MapsApi";
let GET_MAP_MARKER = map+"/GetMap"
let SAVE_MAP_API = map+"/PostMap";
let EDIT_MAP_API = map+"/PutMap/";
let DELETE_MAP_API = map+"/DeleteMap/";

let LOAD_MAP = 'LOAD_MAP';
let SAVE_MAP_ACTION = 'SAVE_MAP_ACTION';
let EDIT_MAP_ACTION = 'EDIT_MAP_ACTION';
let DELETE_MAP_ACTION = 'DELETE_MAP_ACTION';

//Area
let area = base+"/AreaApi";
let GET_ALL_AREA = area+"/GetArea"
let SAVE_AREA_API = area+"/PostArea";
let GET_AREA_BY_ID_API = area+"/GetArea/";
let EDIT_AREA_API = area+"/PutArea/";
let DEL_BATCH_API = area+"/DeleteBatchArea";
let CREATE_NEW_AREA_API = area+"/CreateNewArea"

let GET_ALL_AREA_ACTION ="GET_ALL_AREA_ACTION";
let SAVE_AREA_ACTION='SAVE_AREA_ACTION';
let LOAD_AREA_BY_ID_ACTION='LOAD_AREA_BY_ID_ACTION';
let EDIT_AREA_ACTION = 'EDIT_AREA_ACTION';

let LIST_AREA_LOADED = "LIST_AREA_LOADED";
let AREA_SAVED = "AREA_SAVED";
let AREA_LOADED="AREA_LOADED";


//Employee
let employee = base+"/EmployeesApi";
let EMPLOYEE_CREATE_NEW_API = employee+"/CreateNewEmployee";
let EMPLOYEE_GET_ALL_API = employee+"/GetEmployee";
let EMPLOYEE_GET_ALL_PAGING_API = employee+"/GetListPagingEmployee";
let EMPLOYEE_GET_BY_ID_API = employee+"/GetEmployee/";
let EMPLOYEE_SAVE_API = employee+"/PostEmployee";
let EMPLOYEE_EDIT_API = employee+"/PutEmployee/";
let EMPLOYEE_DEL_BATCH_API = employee+"/DeleteBatchEmployee";

let EMPLOYEE_GET_ALL_ACTION ="EMPLOYEE_GET_ALL_ACTION";
let EMPLOYEE_SAVE_ACTION='EMPLOYEE_SAVE_ACTION';
let EMPLOYEE_LOAD_BY_ID_ACTION='EMPLOYEE_LOAD_BY_ID_ACTION';
let EMPLOYEE_EDIT_ACTION = 'EMPLOYEE_EDIT_ACTION';

let EMPLOYEE_LIST_LOADED = "EMPLOYEE_LIST_LOADED";
let EMPLOYEE_SAVED = "EMPLOYEE_SAVED";
let EMPLOYEE_LOADED="EMPLOYEE_LOADED";


//login
let authentication = base+"/UsersApi";
let LOGIN_API = authentication+"/LoginByUserName"

let LOGIN_ACTION = "LOGIN_ACTION";
let LOGOUT_ACTION = "LOGOUT_ACTION"

let LOGIN_FAILED = "LOGIN_FAILED"


//Weather
let WEATHER_API = "http://api.openweathermap.org/data/2.5/forecast/daily";
let APP_ID="3525816ba73f9ba86251aa56ec4c47cd";
let WEATHER_IMAGE_URL="http://openweathermap.org/img/w/";

//JWT
let JWT_REQUEST = base+"/jwt";

//Common Action
let PROP_CHANGE = "PROP_CHANGE";
let PROP_RESET = "PROP_RESET";
let FETCHING_DATA = "FETCHING_DATA";
let FETCHING_DONE = "FETCHING_DONE";
let SHOW_SNACKBAR_ACTION = "SHOW_SNACKBAR_ACTION";
let CLOSE_SNACKBAR_ACTION = "CLOSE_SNACKBAR_ACTION";  
let LIST_LOADED = "LIST_LOADED";

let CREDENTIAL = "credential";
let SOCKET = io.connect('http://localhost:3000');
	
export default {
  LOAD_MAP,
  GET_MAP_MARKER,
  SAVE_MAP_ACTION,
  SAVE_MAP_API,
  EDIT_MAP_ACTION,
  EDIT_MAP_API,
  DELETE_MAP_ACTION,
  DELETE_MAP_API,
  GET_ALL_AREA,
  GET_ALL_AREA_ACTION,
  SAVE_AREA_ACTION,
  SAVE_AREA_API,
  LOAD_AREA_BY_ID_ACTION,
  GET_AREA_BY_ID_API,
  EDIT_AREA_ACTION,
  EDIT_AREA_API,
  LOGIN_ACTION,
  LOGIN_API,
  WEATHER_API,
  APP_ID,
  WEATHER_IMAGE_URL,
  JWT_REQUEST,  
  LIST_AREA_LOADED,
  DEL_BATCH_API,
  AREA_SAVED,
  AREA_LOADED,
  LOGOUT_ACTION,
  LOGIN_FAILED,
  PROP_CHANGE,
  LIST_LOADED,
  PROP_RESET,
  FETCHING_DATA,
  FETCHING_DONE,
  CREDENTIAL,
  SHOW_SNACKBAR_ACTION,
  CLOSE_SNACKBAR_ACTION,
  CREATE_NEW_AREA_API,

  EMPLOYEE_GET_ALL_API , 
  EMPLOYEE_GET_ALL_PAGING_API,
  EMPLOYEE_SAVE_API ,
  EMPLOYEE_GET_BY_ID_API , 
  EMPLOYEE_EDIT_API , 
  EMPLOYEE_DEL_BATCH_API ,
  EMPLOYEE_CREATE_NEW_API ,

  EMPLOYEE_GET_ALL_ACTION ,
  EMPLOYEE_SAVE_ACTION,
  EMPLOYEE_LOAD_BY_ID_ACTION,
  EMPLOYEE_EDIT_ACTION , 

  EMPLOYEE_LIST_LOADED , 
  EMPLOYEE_SAVED,
  EMPLOYEE_LOADED,
  SOCKET,
};
